services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    secrets:
      - db-name
      - db-user
      - db-password
      - app-user
      - app-password
      - app-db-name
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db-user
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - APP_USER=/run/secrets/app-user
      - APP_PASSWORD=/run/secrets/app-password
      - APP_DB_NAME=/run/secrets/app-db-name
    command: ["postgres", "-N", "1000"]
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U `cat $$POSTGRES_USER_FILE` -d `cat $$POSTGRES_DB_FILE` -c 'SELECT 1;' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-name:
    file: secrets/db_name.txt
  db-user:
    file: secrets/db_user.txt
  db-password:
    file: secrets/db_password.txt
  app-user:
    file: secrets/app_user.txt
  app-password:
    file: secrets/app_password.txt
  app-db-name:
    file: secrets/app_db_name.txt
